### PR TITLE
Add Terraform module for setting up AWS Simple Email Service

### PR DESCRIPTION
**Pull request by The-smooth-operator**

### CODE REVIEW

**Comment by danielhartnell** [comment]
You may already be aware of Terraform data sources but I thought I might mention it here to populate the zone_id.

https://www.terraform.io/docs/providers/aws/d/route53_zone.html

You can use it in `ses.tf` to query the account for the zone_id of whatever domain you want to use if it already exists.

Something like:

```
data "aws_route53_zone" "selected" {
  name         = "test.com."
}
...
zone_id = "${data.aws_route53_zone.selected.zone_id}"
```

**Comment by The-smooth-operator** [comment]
Thanks for the tip. I was aware of Terraform data sources but didn't came to my mind to use it in this case. 
I've applied the changes, I think it looks better with a name than an id.

**Comment by danielhartnell** [comment]
You're welcome to merge this if you want. With the Terraform structural changes (on the development branch), we may want to wait to find a better place for this.

**Comment by The-smooth-operator** [comment]
Closing this out as we don't need to send emails for the moment.

**Pull request closed without merging**
